language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vitepress/dist
  repo: klwfwdk/klwfwdk.github.io
  target_branch: master
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master